version: '3.7'
services:
 database:
  image: mysql
  ports:
    - 3306:3306
    - 33060:33060
  hostname: dbserver
  environment:
    MYSQL_ROOT_PASSWORD: root
 webserver:
  image: tomcat
  ports:
   - 8080:8080
  environment:
   JDBC_URL: jdbc:mysql://dbserver:3306/acs
   JDBC_USER: root
   JDBC_PASSWORD: root
  depends_on:
   - database
