version: '3.7'
services:
			
	database:
		image: mysql
		port:
			- 3306:3306
			- 33060:33060
		environment:
			MYSQL_ROOT_PASSWORD: root
			MYSQL_DATABASE: acs
			MYSQL_USER: abc
			MYSQ_PASSWORD: abc123
			
	webserver:
		image: tomcat
		port:
			- 8080:8080
		environment:
			JDBC_URL: jdbc:mysql://database:3306/acs?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
			JDBC_USER: abc
			JDBC_PASSWORD: abc123
		links:
			- database
			